choderalab/openmoltools

- .travis.yml
- devtools/ci/install.sh
- devtools/conda-recipe/meta.yaml
- gaff2xml/tests/test_drugs.py
- gaff2xml/tests/test_drugs_no_oechem.py
- gaff2xml/tests/test_freesolv.py
Key idea: we don't want to hard-code checks for our CI framework (jenkins vs travis) into our nosetests.  So instead, we just be sure to tag things that are slow as slow and skip running those during the conda-build.
> Switched from hard-coded jenkins / travis detection in tests to nose attribute 'slow'

- gaff2xml/openeye.py
Modifying generate_conformers to default to using loose MMFF atom
typing (to allow coverage of a wider range of molecules)
> Edit omega.generate_conformers to resolve #97

- openmoltools/tests/test_utils.py
- openmoltools/utils.py
Adding a utilities function which assigns functional group descriptors to compounds from a file; added a test thereof to the test_utils.py module. Checkmol is required for this to work. Test will be skipped (and function will raise an exception) if checkmol is not present.
> Adding assignment of checkmol functional group descriptors

- openmoltools/tests/test_drugs.py
Addressing part of issue #109 - one of the slow tests was not labeled with the `slow` attribute.
> Fixing test_drug function to be labeled as slow.

- openmoltools/packmol.py
- openmoltools/tests/test_packmol.py
Addressing issue #111 by implementing `approximate_volume_by_density` in packmol.py; this allows for estimation of box volumes based on the expected density of the mixture rather than based on an estimated molecular volume. Also implemented a test of this functionality.
This is not used (even optionally) by `pack_box` so it will not affect any existing pipelines. My group will be using this in-house and if there is interest later in adjusting `packmol.pack_box` to allow this box selection option to be chosen by the user, we can think about doing so. Note however that this would require some adjustments, as `approximate_volume_by_density` needs to obtain the molecular weight if the components of the system, which I currently do by taking their SMILES strings rather than their file names …
> Implementing an alternative box volume estimator in `packmol.py` without affecting any existing code

- openmoltools/__init__.py
- openmoltools/gromacs.py
- openmoltools/tests/test_gromacs.py
This adds supporting tools for setting up simulation input files (topology and coordinates) with GROMACS. To some extent this could already be done using acpype (with an interface under `utils`); however, if solvated systems were set up in tleap and converted to GROMACS format, the resulting topology files were cumbersome, inefficient, and unsuitable for automated free energy calculations (since all components of the system end up as part of one huge GROMACS "molecule"). An alternate approach - which the tools here will support - is to convert the topology files of the system's components to GROMACS format, then merge these to create a topology file for the full system. 
Most of the basic functionality is here, but I still need to add tests.
> Add GROMACS module, GROMACS support for setting up mixtures for solvation free energy calculations

- openmoltools/gromacs.py
Also fixing an issue where the wrong molecule number could be edited when modifying molecule numbers in topology files where names were not also provided.
> Fix issues relating to whitespace handling in [ molecules ] section in GROMACS topologies

- openmoltools/amber.py
- openmoltools/tests/test_amber.py
- openmoltools/tests/test_utils.py
- openmoltools/utils.py
Attempting to handle #94 and #102 - moving AMBER functionality from `utils` to `amber` (leaving skeleton function calls in place for backwards compatibility) while also adding some processing of AMBER `tleap` and `antechamber` outputs to look for obvious errors, eliminating some silent failures.
Also at the same time added checking of tleap-input filenames for spaces, which result in failures as tleap  can't handle filenames containing spaces.
> AMBER changes - move functions from utils to amber; parse output for errors

- openmoltools/gromacs.py
Gromacs environment variable had to be changed to remove conflicts between the check_for_errors function and the cool quotes printed with the word 'error' on them.
> Added the proper environment variable that suppresses the end-of-file GMX quotes

- devtools/conda-recipe/meta.yaml
This fixes the inability of travis-ci to upload `openmoltools-dev` packages to binstar.
See https://github.com/omnia-md/conda-recipes/pull/226#issuecomment-112937973
> Changed conda package recipe name to openmoltools-dev

- openmoltools/openeye.py
The function normalize_molecule(mol) returns a copy of mol, but this is not used in smiles_to_oemol().
> Fix bug normalization molecule from SMILES to OEMol.

- openmoltools/amber.py
- openmoltools/gromacs.py
- openmoltools/tests/test_amber.py
- openmoltools/tests/test_utils.py
Revised a number of functions in the `amber` module to remove AMBER (`tleap`/`teleap` and `antechamber`)-imposed limitations on characters which were allowed in filenames - formerly no spaces were allowed in filenames. Now work involving antechamber or tleap is done in a temporary directory with hard-coded filenames, and results are copied to/from user-specified filenames, so that now anything which is a valid filename ought to be correctly handled.
Updates were in particular (in `openmoltools.amber`) to:
* run_tleap
* build_mixture_prmtop
* run_antechamber
At the same time I also made a couple of minor fixes to the tests (specifically, amber modules from `utils` were still being used (resulting in a warning and a call to the correct version) rather than the correct versions from …
> Adjusting several functions in the amber module to remove AMBER- and GROMACS- imposed limitations on filenames

- devtools/conda-recipe/meta.yaml
Resolve #128 by making build and run requirements match (though I've not exhaustively checked all of these requirements); also (more importantly) now require openmm rather than openmm-dev. Previously we required openmm-dev as for a while we required features in openmm 6.3 which was not released yet. Now that it is out, it's reasonable to go back to the stable version as a requirement. 
Once this (or any updates/corrections) are merged we should release a new openmoltools version, as the water functionality incorporated by #142 is significant enough for a new point release (as is #147 and possibly others). This will also make it easier for people in my group using the conda install.
> Updating meta.yaml to make build and run requirements match (#128)

- openmoltools/acpype.py
- openmoltools/amber.py
- openmoltools/gromacs.py
- openmoltools/utils.py
The module ``commands`` is deprecated in Python and conflicts with ``yank.commands`` module. This PR substitute the imports
```python
try:
from subprocess import getoutput  # If python 3
except ImportError:
from commands import getoutput  # If python 2
```
in the various ``openmoltools`` modules with
```python
try:
from subprocess import getoutput  # If python 3
except ImportError:
getoutput = openmoltools.utils.getoutput_py2  # If python 2
```
> Remove deprecated module commands

- .travis.yml
- openmoltools/forcefield_generators.py
- openmoltools/tests/test_forcefield_generators.py
This is the beginning of a PR to compare energy components with a prmtop route for loading parameters.
Currently, the test fails because the imatinib `prmtop` seems to lead to very different nonbonded forces:
```
Energy components:
NonbondedForce  -203.736379    31.680160 :   235.416539
HarmonicBondForce     6.160988     6.248384 :     0.087396
HarmonicAngleForce     5.330822     5.329843 :     0.000980
PeriodicTorsionForce    13.253722     8.783295 :     4.470427
CMMotionRemover     0.000000     0.000000 :     0.000000
Maximum allowed deviation (0.600000) exceeded.
```
I'm not sure why this is, but I am investigating.  I also don't know the origin of the `chemicals/imatinib/imatinib.prmtop` file.
It may be better for me to compare with a `prmtop/inpcrd` generated on the fly from either …
> Compare energy components with antechamber/prmtop route

- openmoltools/forcefield_generators.py
- openmoltools/parameters/gaff.xml
- openmoltools/tests/test_forcefield_generators.py
* Implement #187.
* Also fixes #189, except that atom names are replaced with Tripos atom names rather than throwing an exception.
This doesn't work yet because mol2 files are not processed as residues by `parmed`:
https://github.com/ParmEd/ParmEd/issues/592
> Implementing generation of ffxml files for multiple molecules

- openmoltools/tests/test_forcefield_generators.py
This disables `Exception`s arising from https://github.com/choderalab/openmm/issues/8 from being reported until this is fixed in `openmm`.
> Comment out exception for known bug in openmm

- openmoltools/amber.py
- openmoltools/gromacs.py
- openmoltools/openeye.py
- openmoltools/schrodinger.py
- openmoltools/tests/test_schrodinger.py
- openmoltools/tests/test_utils.py
- openmoltools/utils.py
This PR I have added wrapper functions to Schrodinger's tools ``epik``, ``structconvert``, ``maesubset`` and ``proplister``. I also removed ``logging`` configurations from non-test modules (see #194).
In the last commit, I removed a test for ``enter_temp_directory()`` which is an ``mdtraj`` function, not ``openmoltools``.
> Schrodinger suite wrapper functions and removed logging configuration

- openmoltools/schrodinger.py
Added the option to use the minimum probability (`-p`) option to `openmoltools.schrodinger.run_epik`.
> Add -p option to run_epik.

- devtools/conda-recipe/meta.yaml
- openmoltools/forcefield_generators.py
@davidlmobley, your binary mixture tests are also failing on travis and I don't know why:
```
======================================================================
ERROR: test_amber.test_amber_box
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
self.test(*self.arg)
File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/openmoltools-0.7.0.dev0-py2.7.egg/openmoltools/tests/test_amber.py", line 19, in test_amber_box
box_trj = packmol.pack_box(trj_list, [50])
File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/openmoltools-0.7.0.dev0-py2.7.egg/openmoltools/packmol.py", line 102, in pack_box
trj = …
```
> Fix test failures

- openmoltools/forcefield_generators.py
As discussed in #208 , this PR adds an option (default `False`) to `generateForceFieldFromMolecules` to allow charging to fail gracefully and have the resultant molecules added to a failure list, which is returned along with the `ffxml` string. If the option is left at `False`, then the list will be empty and the function will behave as previously (exception).
> Option to fail charging gracefully

- setup.py
Do we want to wait for Christopher Bayly comments on the new OpenEye warnings (see #201) before releasing or can I proceed?
> Prepare setup.py for release 0.7.0

- .travis.yml
- openmoltools/forcefield_generators.py
Because of changes in https://github.com/pandegroup/openmm/pull/1373 we now need to ensure residue template names are globally unique.
In this PR:
* residue templates generated on the fly are named as `[resname]-[uuid]`
* residue templates generated in batch calls have an option to use the same globally unique naming scheme
cc: https://github.com/choderalab/perses/pull/195
> Generate globally unique residue template names

- openmoltools/gromacs.py
- openmoltools/utils.py
Earlier versions of ParmEd could harm GROMACS files (modifying FudgeLJ and FudgeQQ to incorrect values). This adds version checks to ensure ParmEd version is new enough.
> Add ParmEd version check needed for GROMACS functionality

- setup.py
I wanted to wait for the release on omnia/conda-recipes and I ended up forgetting to set the version to dev in `setup.py`. This is ready to be merged.
> Set setup.py version to 0.7.1dev0 for ongoing development

- .travis.yml
- devtools/conda-recipe/meta.yaml
This re-activates RDKit as a requirement as per #221 to allow the existing `packmol` tests to work.
I expect that this will initially fail at least on the OpenEye betas because of #219 ; it may also fail because of https://github.com/omnia-md/conda-recipes/issues/512 - library issues with omnia RDKit.
> Re-activate RDKit as requirement to enable testing of packmol tools.

- openmoltools/schrodinger.py
- openmoltools/utils.py
I have added to `utils` a couple of wrapping utilities that allow to retrieve `ArgSpec` for wrapped functions also in Python 2.
> Add Python 2-3 compatibile wrapping functions

- openmoltools/system_checker.py
- openmoltools/tests/test_packmol.py
Adding more informative output information to `system_checker` for comparing details of `OpenMM` systems, as per #227 .
So far I just added additional info for periodic torsional forces. I'll be adding this in the order in which I need it.
> Add more informative info to system_checker

- openmoltools/system_checker.py
Modifies a print statement to be more informative, and adds an optional argument to allow bypassing of an assertion relating to impropers when desired (since in SMIRFF forcefields we use a different form for impropers than in AMBERS, so the force terms are supposed to be different).
> Minor tweaks to system_checker for better debugging in smarty

- devtools/travis-ci/install.sh
Why:
Currently, builds are experiencing an md5 checksum issue.
This command is broken due to some change on either the webpage, or perhaps
curl, leading to an empty md5 sum to check against.
This change addresses the need by:
* Updating the url to https.
> Update devtools miniconda url

- .travis.yml
OpenEye no longer provides ubuntu 12.04 builds. This switches to the new unified linux-x64 builds.
> Update OpenEye installation to unified build

- openmoltools/amber_parser.py
Work in progress. Fixes #235 .
Why:
The Amber .dat format has a fixed width specification.
The previous implementation simply splits by column, which
breaks when it encounters lines such as :
`c1-sh-hs   48.23       95.99	calculated_based_on_C#C-SH       00`
This change addresses the need by:
* Replacing the .dat parsing code in AmberParser with functions
that parse lines according to the fixed-width format.
* Explicitly naming the variables according to the Amber format,
so it is clearer from the code what is being stored.
> Use .dat fixed width format

- openmoltools/forcefield_generators.py
Why:
By default, the template/ForceField generators normalize the molecule in terms of atom and residue name. There are use cases where it is preferable to maintain the input names.
I added an option to prevent normalization. The default produces the
current behavior.
This change addresses the need by:
* Adding new keyword argument 'normalize' to
- `generateResidueTemplate`
- `generateForceFieldFromMolecules`
* Passing this to the normalize flag of the `get_charges` command.
> Add normalize option to template generators

- openmoltools/forcefield_generators.py
- openmoltools/openeye.py
- openmoltools/tests/test_openeye.py
The molecule_to_mol2 function uses a high-level writer,
which overwrites atomic properties such as atom names in an effort to standardize them.
Sometimes it is desirable to keep the atom names provided in the input.
This change addresses the need by:
* An option called `standardize` is added to molecule_to_mol2
* (Some) functions that depend on it have been updated to
make it accessible.
* Tests of the mol2 reading have been added to validate
that behavior is as expected.
> Add standardize to mol2 output

- openmoltools/system_checker.py
Fix a small bug in units of `qq` (product of two scaled charges) in system checker which resulted in a failure of a print statement when an error was caught.
> Fix unit issue in charge component of nonbonded system checker

- devtools/conda-recipe/meta.yaml
- openmoltools/amber.py
- openmoltools/system_checker.py
- setup.py
Previously, I adjusted `run_tleap` to allow alternate `leaprc` files to be used, such as for GAFF2 ( #233 ). However, GAFF2 also uses (in some cases) different atom typing it seems -- at least, `antechamber` has options to assign both GAFF and GAFF2 types.
This PR adds the option to select `gaff2` types when running `antechamber`. The default is to the normal behavior (`gaff` types).
> Adjust antechamber functionality to allow for gaff2 types

- setup.py
In #245 I brought in some changes I need to roll out in a release for use on Orion, so this adjusts `setup.py` to make the version number 0.7.5 for a release.
> Change version # for a release

- devtools/travis-ci/install.sh
Conda build does not work with --yes and --use-local automatically since conda-build=2.1.6, so pin this until they fix it
> Pin conda-build to 2.1.5 until its fixed

- openmoltools/packmol.py
- openmoltools/tests/test_packmol.py
This implement a function to solve the problem brought up in #253 . Currently it's a separated function `packmol.standardize_water` that can optionally be called on a water molecule to standardize its residue/atom names and make MDTraj automatically perceive bonds. Right now I preferred this to making it all automatic and hidden inside `packmol.pack_box` because
1) It'd involve loading as a `Trajectory` object every molecule before invoking packmol to check if it is a water.
2) I'd prefer `packmol.pack_box` to not have unexpected side effects on the output files.
We can always integrate the two functions later if we notice significant advantages. Currently this is how it works
```python
>>> water_traj = mdtraj.load('water.pdb')
>>> is_water = packmol.standardize_water(water_traj)
>>> …
```
> Implement function to standardize_water

- .travis.yml
- openmoltools/openeye.py
- openmoltools/tests/test_openeye.py
Addressing issue #252 by replacing the line to call the `OEAssignCharges` from OEToolkits version 2017.02.01. Added some warning messages as well.
> Update for OEAssignCharges

- openmoltools/forcefield_generators.py
- openmoltools/parameters/gaff2.xml
- openmoltools/tests/test_forcefield_generators.py
This adds gaff2 as an option for forcefield template generators.
Note that I borrowed a gaff2 xml file from @rafwiewiora, 
Source and commit hash: https://github.com/choderalab/openmm-forcefields/blob/5e26b3996b6422ae477c3a1a5f8ad095ef588897/amber/ffxml/gaff2.xml
> Gaff2 template generator

- openmoltools/packmol.py
- openmoltools/tests/test_packmol.py
- setup.py
Packmol does not support periodic boundary conditions. Their [docs suggests](http://www.ime.unicamp.br/~martinez/packmol/userguide.shtml#pbc) to pack the molecules in a box 2 angstroms smaller.
I've also made a modification to `openmoltools.pack_box` so that all temporary files created by the function are deleted at the end of the execution (`tempfile.mktemp` does not delete them automatically).
> Apply packmol docs suggestions for box size with PBC

- .travis.yml
- README.md
- devtools/conda-recipe/meta.yaml
Remove the libgfotran pinned dependency as its been almost 2 years since that fix went in. I'm assuming SciPy should have fixed its problems related to that and pinning to 1.0 seems backwards as it now has a 3.0 release. 
Any objections or reasons this should not happen, @jchodera, @davidlmobley ?
> Remove Libgfortran dependency pin

- .travis.yml
- setup.py
Also switches OpenEye source location from `pip` to `conda`
Stops tests on Python 2.7
> Bump to 0.9.0

- openmoltools/openeye.py
- openmoltools/tests/test_openeye.py
I added an option to write out all conformers in a multiconformer molecule to mol2 file.
> Write out multiple conformers

- .travis.yml
- devtools/conda-recipe/meta.yaml
- openmoltools/forcefield_generators.py
In openmm 7.4, the class `_TemplateData` has a dictionary attribute `atomIndices`, which is populated by the function `addAtom()`, which is also not in previous openmm's.
`atomIndices` are required to use the function `getAtomIndexByName()`.
This PR allows for compatibility for both omm 7.3 and 7.4, with the 7.4-specific code in the comments for future use.
> fixing forcefield_generators to be compatible with openmm 7.4

- openmoltools/forcefield_generators.py
Closes #279 and #295
This should fix the issue where antechamber is failing for bond type perception. Bondtype can be used as it's now shipped with AmberTools.
> reverting back to using bondtype instead of antechamber

- openmoltools/packmol.py
Relatively recently, OpenMM added bond order handling, but our `packmol` module had not been updated to handle this, causing failures -- specifically, the `bonds` array passed into `mdtraj.topology.from_dataframe` now has four entries per bond ( `(atom1, atom2, type1, order)`) but the logic here was still treating it as if it only contained atoms. This resulted in `type1` and `order` getting set to numbers larger than or equal to the number of atoms in the system, causing downstream failures.
This fixes the issue.
> Fixes `packmol` module compatibility with recent OpenMM and MDTraj versions

- README.md
Since we have converted to GitHub Actions, remove the badge for travis.
> Remove travis badge from README

- setup.py
In preparation for conda-forge, I am trimming dependencies to the minimum. Numpy and Cython are null imports in setup.py and _not_ needed. Seems to be more like a template leftover. This should be into a patch release.
> Remove unneeded deps in setup.py

- .github/workflows/CI.yaml
- README.md
- openmoltools/amber_parser.py
- openmoltools/forcefield_generators.py
- openmoltools/tests/test_amber.py
- openmoltools/tests/test_utils.py
Fixes #303: There are changes happening in the openmm namespace, this should allow us to take advantage of the backwards compatible changes in the name space. 
Also the README was pointing to the wrong CI badge, fixing that as well in this PR
> Update for OpenMM namespace changes
