choderalab/openmoltools

gaff2xml/tests/test_common_molecules.py
This builds in a test of `catechol` and `aspirin` and some other common molecules.
The test currently fails.  Debugging now...
=> Added test of common molecules to illustrate failures

openmoltools/tests/test_drugs.py
=> [WIP] Potential fix for #79

openmoltools/amber.py, openmoltools/tests/test_openeye.py, openmoltools/utils.py
I'm still fixing a bug in this, but should be done soonish.
=> Automated resname randomization

openmoltools/__init__.py, openmoltools/acpype.py, openmoltools/tests/test_utils.py, openmoltools/utils.py
* Implement acpype conversion of AMBER prmtop/crd files to GROMACS format (in `utils.py`)
* Include `acpype.py` in package
* Adding D. Mobley authorship to `__init__.py`. 
* Implement acpype conversion testing in `utils/test_utils.py` (**not yet tested due to slowness in running tests**)
* Fix a documentation error in `run_tleap` within `utils.py`
=> Implementing acpype conversion of AMBER prmtop/crd files to GROMACS and associated changes

openmoltools/gromacs.py, setup.py
Minor cosmetic (spacing) adjustments in merged gromacs topology files created via gromacs utilities. 
Incremented version counter in setup.py from 0.6.5.dev0 (incorrect) to 0.6.7.dev0 since we already released 0.6.6.
=> Cosmetic adjustments in gromacs.py; increment version counter in setup.py

.travis.yml
This will hopefully address part of https://github.com/omnia-md/conda-recipes/pull/226#issuecomment-112937973
=> Update expired encrypted BINSTAR_TOKEN

.travis.yml
Another attempt to update this.
=> Updated secure BINSTAR_TOKEN

.travis.yml
Another attempt to update this.
=> Another attempt to update BINSTAR_TOKEN

.binstar.yml, .travis.yml
Still trying to debug the `openmoltools-dev` builds.
Also experimenting with `binstar-build`.
=> Updates to BINSTAR_TOKEN for openmoltools-dev builds; experimental binstar-build

.travis.yml
Attempt to address issue seen in #142.
=> Don't decrypt OpenEye license in pull requests

openmoltools/openeye.py, openmoltools/tests/test_openeye.py
Added an optional keyword argument, and a unit test that sets it to False.
=> Make normalize optional in openeye.get_charges

.travis.yml, devtools/travis-ci/install.sh
Some things recently broke on travis.
=> Fix travis

devtools/travis-ci/install.sh, openmoltools/openeye.py, openmoltools/tests/test_common_molecules.py
Also clean up conda environment activation issue.
=> Revert behavior of SMILES and IUPAC molecule generation; fix test.

openmoltools/amber.py, openmoltools/tests/test_amber.py
=> Add resname option to run_antechamber.

setup.py
=> Updating setup.py for ongoing development

openmoltools/parameters/gaff.xml
This adds a test version of `gaff.xml` to be installed in `openmoltools/parameters/gaff.xml`
=> Add gaff.xml to distro

openmoltools/amber.py, openmoltools/openeye.py
Logging is now turned off for these by default.
=> Allow logging to be turned off for run_tleap and run_antechamber

openmoltools/forcefield_generators.py, openmoltools/tests/test_forcefield_generators.py
This adds `SystemGenerator`, a wrapper for generating OpenMM systems from `Topology` objects with prespecified options.
=> Added SystemGenerator and tests

openmoltools/schrodinger.py
=> Fix bytes decoding for python 3 compatibility

openmoltools/forcefield_generators.py, openmoltools/tests/test_forcefield_generators.py
This addresses #203. If the test passes, then it should be good to merge.
=> Retain topology index in oemol

openmoltools/tests/test_forcefield_generators.py
=> Fix test generator problem with OpenMM system creation

openmoltools/forcefield_generators.py
This should fix issues with blocked amino acid residues.
=> Fixes to generateOEMolFromTopologyResidue

.travis.yml, devtools/conda-recipe/meta.yaml
The `BINSTAR_TOKEN` had expired.
=> Fix binstar upload

devtools/conda-recipe/meta.yaml, devtools/travis-ci/install.sh
cc: https://github.com/mila-udem/blocks/issues/836#issuecomment-142112468
cc: https://github.com/choderalab/yank/pull/354
=> Add libgfortran to run dependencies to work around scipy issues

openmoltools/amber.py, openmoltools/tests/test_amber.py
Added a method to build a peptide with tleap, and a simple test.
=> Add method to build peptide

setup.py
Increment version number for development
=> Update setup.py for ongoing development

setup.py
As title says. Dev version will be bumped to 0.9.0 to indicate major support change for future releases
=> Cut official 0.8.3 release - Final Py27

openmoltools/openeye.py
Would resolve #280 .
@ChayaSt or @andrrizzi do you mind doing a quick check so we can merge? (A student of mine was trying to set up calculations on a bunch of neutral zwitterions -- +1 at one end and -1 at the other -- and ran into the issue where the desired compounds just came out neutral at both ends.)
=> Modify `smiles_to_antechamber` to allow optional use of protonation model

openmoltools/openeye.py
updating to oequacpac.OEAM1BCCELF10Charges
=> [WIP] updating to openeye charging methods
